name: First workflow

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "server/**"
      - "client/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "server/**"
      - "client/**"
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Display a greeting
        run: echo "Hello from GitHub Actions"
